services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Strongpa$$w0rd!
      MYSQL_DATABASE: bdEfren
      MYSQL_USER: efren
      MYSQL_PASSWORD: Strongpa$$w0rd!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  uttt-micro-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=bdEfren;user=efren;password=Strongpa$$w0rd!;
    depends_on:
      - mysql

volumes:
  mysql_data:
